# Generated by Django 3.0.8 on 2020-07-16 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200716_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
